### ISSUE TITLE
运行源码 报错了

### ISSUE THREAD

**Issue by zhEdward** [miyouzi/akamTester#2]
> MacOS Mojave Platform

git下来  安装依赖，执行语句，后续报错了

```
(master)⚡ % python3 akamTester.py > akamtester_log.txt          ~/Desktop/akamTester
第一次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

第二次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

第三次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

共取得 69 个 IP, 开始测试延迟

Traceback (most recent call last):
  File "akamTester.py", line 67, in <module>
    delay = ping_test(ip)
  File "akamTester.py", line 19, in ping_test
    result = ping(ip, count=5)
  File "/usr/local/lib/python3.7/site-packages/pythonping/__init__.py", line 52, in ping
    comm = executor.Communicator(target, provider, timeout, socket_options=options, verbose=verbose, output=out)
  File "/usr/local/lib/python3.7/site-packages/pythonping/executor.py", line 224, in __init__
    self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)
  File "/usr/local/lib/python3.7/site-packages/pythonping/network.py", line 25, in __init__
    self.socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, self.protocol)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <function Socket.__del__ at 0x1044585f0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pythonping/network.py", line 56, in __del__
    if self.socket:
AttributeError: 'Socket' object has no attribute 'socket'
Exception ignored in: <function Communicator.__del__ at 0x104492170>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pythonping/executor.py", line 233, in __del__
    if self.socket:
AttributeError: 'Communicator' object has no attribute 'socket'
```

**Comment by miyouzi** [comment]
```PermissionError``` 权限问题，Linux下需要```sudo```

**Comment by zhEdward** [comment]
good,可以考虑在 *README.md*里面添加** 这种意外情况说明
