### ISSUE TITLE
测试延迟时报错

### ISSUE THREAD

**Issue by longhuan1999** [miyouzi/akamTester#4]
![QQ截图20200301163358](https://user-images.githubusercontent.com/43313501/75622402-99d39580-5bda-11ea-8f90-e3ddc4a739f6.png)

当前akamTester版本: 4.0
第一次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

第二次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

第三次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

共取得 64 个 IP, 开始测试延迟

Traceback (most recent call last):
  File "akamTester.py", line 80, in <module>
    delay = ping_test(ip)
  File "akamTester.py", line 20, in ping_test
    result = ping(ip, count=5)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pythonping\__init__.py", line 52, in ping
    comm = executor.Communicator(target, provider, timeout, socket_options=options, verbose=verbose, output=out)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pythonping\executor.py", line 239, in __init__
    self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pythonping\network.py", line 22, in __init__
    self.protocol = socket.getprotobyname(protocol)
OSError: protocol not found
Exception ignored in: <function Socket.__del__ at 0x036C4780>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pythonping\network.py", line 60, in __del__
    raise AttributeError("Attribute error because of failed socket init. Make sure you have the root privilege."
AttributeError: Attribute error because of failed socket init. Make sure you have the root privilege. This error may also be caused from DNS resolution problems.

**Comment by miyouzi** [comment]
请问系统具体版本是？

**Comment by longhuan1999** [comment]
windows10
管理员模式运行cmd.exe，再执行akamTester_v4.0.exe，依然报错

C:\Users\longhuan\Desktop\akamTester_v4.0>akamTester_v4.0.exe
当前akamTester版本: 4.0
第一次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

第二次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

第三次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
upos-hz-mirrorakam.akamaized.net 的全球解析已完成

共取得 79 个 IP, 开始测试延迟

Traceback (most recent call last):
  File "akamTester.py", line 80, in <module>
  File "akamTester.py", line 20, in ping_test
  File "site-packages\pythonping\__init__.py", line 52, in ping
  File "site-packages\pythonping\executor.py", line 239, in __init__
  File "site-packages\pythonping\network.py", line 22, in __init__
OSError: protocol not found
[11296] Failed to execute script akamTester
Exception ignored in: <function Socket.__del__ at 0x02DA5588>
Traceback (most recent call last):
  File "site-packages\pythonping\network.py", line 60, in __del__
AttributeError: Attribute error because of failed socket init. Make sure you have the root privilege. This error may also be caused from DNS resolution problems.
