### ISSUE TITLE
能否增加对结果进行导出？

### ISSUE THREAD

**Issue by ausers** [miyouzi/akamTester#5]
因为习惯用批处理省去输入命令的功夫，但是由于批处理难以同时保持回显和导出，能否对结果进行排序并导出？这样我可以方便地在自己的批处理中直接增加写入至hosts的功能

**Comment by miyouzi** [comment]
那下一个版本会将结果输出到文件。

**Comment by ZhangBo1191** [comment]
可以直接用管道吧

**Comment by ausers** [comment]
> 可以直接用管道吧

没搞定，能指导一下吗？我现在是 `echo.|python %~dp0\akamTester.py>%~dp0\results.txt` 导出然后设置完host一股脑把 `results.txt` 显示出来的

**Comment by ZhangBo1191** [comment]
我看看

> > 可以直接用管道吧
> 
> 没搞定，能指导一下吗？我现在是 `echo.|python %~dp0\akamTester.py>%~dp0\results.txt` 导出然后设置完host一股脑把 `results.txt` 显示出来的

**Comment by ausers** [comment]
> 我看看
> 
> > > 可以直接用管道吧
> > 
> > 
> > 没搞定，能指导一下吗？我现在是 `echo.|python %~dp0\akamTester.py>%~dp0\results.txt` 导出然后设置完host一股脑把 `results.txt` 显示出来的

https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat
这是我目前的实现方式。。。

**Comment by ZhangBo1191** [comment]
@ausers 所以要求是把最快的ip写到hosts对吧

**Comment by ausers** [comment]
> @ausers 所以要求是把最快的ip写到hosts对吧

想法是这样，不过不显示回显等大半天的话不好看，所以想找个能同时回显并导出的方法

**Comment by ausers** [comment]
最主要还是米柚子咕太久了(确信)，他要是不咕了咱就可以省去这一步了2333

**Comment by ZhangBo1191** [comment]
> > @ausers 所以要求是把最快的ip写到hosts对吧
> 
> 想法是这样，不过不显示回显等大半天的话不好看，所以想找个能同时回显并导出的方法

如果是这样的话，直接改python文件会更好吧

**Comment by ZhangBo1191** [comment]
我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法

**Comment by ausers** [comment]
> > > @ausers 所以要求是把最快的ip写到hosts对吧
> > 
> > 
> > 想法是这样，不过不显示回显等大半天的话不好看，所以想找个能同时回显并导出的方法
> 
> 如果是这样的话，直接改python文件会更好吧

我挺少直接改Python的，一方面是不会，另一方面……懒👀

**Comment by ZhangBo1191** [comment]
> @ausers 所以要求是把最快的ip写到hosts对吧

测试下 https://github.com/ZhangBo1191/akamTester/master

**Comment by ZhangBo1191** [comment]
> 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法

@ausers  试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
@miyouzi 已提交PR

**Comment by ausers** [comment]
> > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> 
> @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> @miyouzi 已提交PR 见 #6

Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
`'sudo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak
Traceback (most recent call last):
  File "akamTester.py", line 124, in <module>
    if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"):
  File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp
    s2 = _sig(os.stat(f2))
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
power shell报错与此一致

**Comment by ZhangBo1191** [comment]
> > > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> > 
> > @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> > @miyouzi 已提交PR 见 #6
> 
> Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
> `'sudo' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak
> Traceback (most recent call last):
>   File "akamTester.py", line 124, in <module>
>     if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"):
>   File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp
>     s2 = _sig(os.stat(f2))
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
> power shell报错与此一致

知道了

**Comment by ZhangBo1191** [comment]
> > > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> > 
> > 
> > @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> > @miyouzi 已提交PR 见 #6
> 
> Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
> `'sudo' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 124, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
> power shell报错与此一致
我把提权删掉了 你用管理员执行试下

**Comment by ZhangBo1191** [comment]
> > > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> > 
> > 
> > @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> > @miyouzi 已提交PR 见 #6
> 
> Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
> `'sudo' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 124, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
> power shell报错与此一致

@ausers 已修复

**Comment by ausers** [comment]
> > > > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> > > 
> > > 
> > > @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> > > @miyouzi 已提交PR 见 #6
> > 
> > 
> > Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
> > `'sudo' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 124, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
> > power shell报错与此一致
> 
> 我把提权删掉了 你用管理员执行试下

`Start-Process -verb runas -filepath cmd.exe -argument /C copy C:\WINDOWS\System32\drivers\etc\hosts C:\WINDOWS\System32
\drivers\etc\hosts_bak
已创建hosts备份文件！备份文件名为“hosts_bak
Traceback (most recent call last):
  File "akamTester.py", line 122, in <module>
    if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"):
  File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp
    s2 = _sig(os.stat(f2))
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`

**Comment by ZhangBo1191** [comment]
> > > > > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> > > > 
> > > > 
> > > > @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> > > > @miyouzi 已提交PR 见 #6
> > > 
> > > 
> > > Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
> > > `'sudo' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 124, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
> > > power shell报错与此一致
> > 
> > 
> > 我把提权删掉了 你用管理员执行试下
> 
> `Start-Process -verb runas -filepath cmd.exe -argument /C copy C:\WINDOWS\System32\drivers\etc\hosts C:\WINDOWS\System32 \drivers\etc\hosts_bak 已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 122, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`

是最新的Commit吗

**Comment by ZhangBo1191** [comment]
> > > > > 我会在我fork的仓库支持直接写入hosts的特性，至于上游我也没办法
> > > > 
> > > > 
> > > > @ausers 试下 [我的仓库](https://github.com/ZhangBo1191/akamTester)
> > > > @miyouzi 已提交PR 见 #6
> > > 
> > > 
> > > Windows下通过批处理管理员执行 `python akamTester.py -t` ，在设置hosts阶段报错：
> > > `'sudo' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 即将创建hosts备份文件，请授予管理员权限已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 124, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`
> > > power shell报错与此一致
> > 
> > 
> > 我把提权删掉了 你用管理员执行试下
> 
> `Start-Process -verb runas -filepath cmd.exe -argument /C copy C:\WINDOWS\System32\drivers\etc\hosts C:\WINDOWS\System32 \drivers\etc\hosts_bak 已创建hosts备份文件！备份文件名为“hosts_bak Traceback (most recent call last): File "akamTester.py", line 122, in <module> if cmp(hostsFolder+"\\hosts", hostsFolder+"\\hosts_bak"): File "C:\Program Files\Python38\lib\filecmp.py", line 52, in cmp s2 = _sig(os.stat(f2)) FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts_bak'`

看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要

**Comment by ausers** [comment]
> 看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要

看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个

**Comment by ZhangBo1191** [comment]
> 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个

你不在最新commit

**Comment by ausers** [comment]
> > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个
> 
> 你不在最新commit

16：35刚从你的库下的

**Comment by ZhangBo1191** [comment]
> > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个
> > 
> > 
> > 你不在最新commit
> 
> 16：35刚从你的库下的

你现在看本地的最新的commit是多少

**Comment by ausers** [comment]
> > > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个
> > > 
> > > 
> > > 你不在最新commit
> > 
> > 
> > 16：35刚从你的库下的
> 
> 你现在看本地的最新的commit是多少

https://github.com/ZhangBo1191/akamTester/archive/master.zip 我是通过这个按钮直接下载的

**Comment by ZhangBo1191** [comment]
> > > > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个
> > > > 
> > > > 
> > > > 你不在最新commit
> > > 
> > > 
> > > 16：35刚从你的库下的
> > 
> > 
> > 你现在看本地的最新的commit是多少
> 
> https://github.com/ZhangBo1191/akamTester/archive/master.zip 我是通过这个按钮直接下载的

你把源文件akamTester.py的第109行发一下

**Comment by ausers** [comment]
> > > > > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的那个
> > > > > 
> > > > > 
> > > > > 你不在最新commit
> > > > 
> > > > 
> > > > 16：35刚从你的库下的
> > > 
> > > 
> > > 你现在看本地的最新的commit是多少
> > 
> > 
> > https://github.com/ZhangBo1191/akamTester/archive/master.zip 我是通过这个按钮直接下载的
> 
> 你把源文件akamTester.py的第109行发一下

`    os.system(r'powershell -command {Start-Process -verb runas -filepath cmd.exe -argument "/C copy %SystemRoot%\System32\drivers\etc\hosts %SystemRoot%\System32\drivers\etc\hosts_bak"}')`

**Comment by ausers** [comment]
哦对比了下确实不同

**Comment by ZhangBo1191** [comment]
……

> 哦对比了下确实不同

**Comment by ausers** [comment]
> 你把源文件akamTester.py的第109行发一下

单独下载了，我再运行下看看，头次知道这下载还会出这岔子的

**Comment by ausers** [comment]
> > 你把源文件akamTester.py的第109行发一下
> 
> 单独下载了，我再运行下看看，头次知道这下载还会出这岔子的

另外下载了`akamTester.py`和`.gitignore`并替换，依然出现相同报错

**Comment by ZhangBo1191** [comment]
> > > 你把源文件akamTester.py的第109行发一下
> > 
> > 
> > 单独下载了，我再运行下看看，头次知道这下载还会出这岔子的
> 
> 另外下载了`akamTester.py`和`.gitignore`并替换，依然出现相同报错

好的

**Comment by ZhangBo1191** [comment]
> > 看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要
> 
> 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的

你先删掉现有的呀，解析出来的IP测出来结果，最快的IP有概率保持一致的

**Comment by ausers** [comment]
> > > 看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要
> > 
> > 
> > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的
> 
> 你先删掉现有的呀，解析出来的IP测出来结果，最快的IP有概率保持一致的

删除现有的确实添加进去了。。。我还以为会覆盖

**Comment by ZhangBo1191** [comment]
> > > > 看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要
> > > 
> > > 
> > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的
> > 
> > 
> > 你先删掉现有的呀，解析出来的IP测出来结果，最快的IP有概率保持一致的
> 
> 删除现有的确实添加进去了。。。我还以为会覆盖

记录一样吗？

**Comment by ausers** [comment]
> > > > > 看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要
> > > > 
> > > > 
> > > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的
> > > 
> > > 
> > > 你先删掉现有的呀，解析出来的IP测出来结果，最快的IP有概率保持一致的
> > 
> > 
> > 删除现有的确实添加进去了。。。我还以为会覆盖
> 
> 记录一样吗？

与最快结果一致，如果能[直接覆盖](https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48)应该会更好用，以及处理掉报错

**Comment by ZhangBo1191** [comment]
参见PR https://github.com/miyouzi/akamTester/pull/6#discussion_r406641935
l另外报错已经处理了
> > > > > > 看看你的hosts记录是不是加上了呢 这个报错如果加上了就无关紧要
> > > > > 
> > > > > 
> > > > > 看了下，没有看到hosts_bak文件，且对应host依然是以前我bat加的
> > > > 
> > > > 
> > > > 你先删掉现有的呀，解析出来的IP测出来结果，最快的IP有概率保持一致的
> > > 
> > > 
> > > 删除现有的确实添加进去了。。。我还以为会覆盖
> > 
> > 
> > 记录一样吗？
> 
> 与最快结果一致，如果能[直接覆盖](https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48)应该会更好用，以及处理掉报错

**Comment by ZhangBo1191** [comment]
@ausers https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48 主程序内不再需要管理员权限

**Comment by ausers** [comment]
> @ausers https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48 主程序内不再需要管理员权限

运行成功，除了不能覆盖其他应该都没问题了

**Comment by ZhangBo1191** [comment]
> > @ausers https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48 主程序内不再需要管理员权限
> 
> 运行成功，除了不能覆盖其他应该都没问题了

重复解析的问题会修复的

**Comment by ausers** [comment]
> > > @ausers https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48 主程序内不再需要管理员权限
> > 
> > 
> > 运行成功，除了不能覆盖其他应该都没问题了
> 
> 解析重复时报错的问题会修复的

指hosts内已经存在`upos-hz-mirrorakam.akamaized.net`条目时的覆盖问题

**Comment by ZhangBo1191** [comment]
> > > > @ausers https://github.com/ausers/bat-for-python/blob/master/%E4%B8%80%E9%94%AE%E6%A3%80%E6%B5%8BB%E7%AB%99CDN.bat#L46-L48 主程序内不再需要管理员权限
> > > 
> > > 
> > > 运行成功，除了不能覆盖其他应该都没问题了
> > 
> > 
> > 解析重复时报错的问题会修复的
> 
> 指hosts内已经存在`upos-hz-mirrorakam.akamaized.net`条目时的覆盖问题
> ![20200410192303](https://user-images.githubusercontent.com/54773815/78987472-b90dfd00-7b60-11ea-90e3-8d8c83d7ab8a.png)

Fixed

**Comment by ausers** [comment]
> Fixed

测试成功

**Comment by MeGuMinEx** [comment]
直接用流就可以把结果输出到文件吧，python3 akamTester.py >> log
